server:
  port: 8081
  servlet:
    context-path: /patient-management

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: andrei
    password: andrei
  h2.console.enabled: true